# Generated by Django 5.1.3 on 2025-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
