# Generated by Django 5.1.3 on 2025-02-15 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_counter', '0002_alreadypaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alreadypaid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
